### ISSUE TITLE
Mixpanel error: "mixpanel" object not initialized

### ISSUE THREAD

**Issue by erickbrenesLT** [wrakky/page-ruler#103]
@wrakky Updated to Chrome 64 and now getting this error with this extension.

Mixpanel error: "mixpanel" object not initialized. Ensure you are using the latest version of the Mixpanel JS Library along with the snippet we provide.
U @ cdn.mxpnl.com/libs/mixpanel-2-latest.min.js:9

Chrome on Mac - Version 64.0.3282.140 (Official Build) (64-bit)
OS - Sierra

**Comment by SWBennett06** [comment]
It really shouldn't be injecting MixPanel Analytics at all... I'm dropping the plugin unless they clean things up.

**Comment by vteremasov** [comment]
Yeah, I am reporting abuse since it violates misrepresents features rule (aka 'App or extension misrepresents its value or features'). I think it should be treated as a trojan. Please, correct me if I'm wrong.

**Comment by doublejosh** [comment]
Cross posting... https://stackoverflow.com/questions/48641577/mixpanel-error-mixpanel-object-not-initialized

**Comment by shoxv** [comment]
So did this guy stop supporting the extension then add some malware to monetize it?
