### ISSUE TITLE
Mixpanel error

### ISSUE THREAD

**Issue by shafqatali** [wrakky/page-ruler#105]
Hi
I hope you will be fine.  It's a nice extension and very helpful for developer. 

I am here to report an issue with this extension version 2.1.1 being used in Chrome Version 64.0.3282.140 (Official Build) (64-bit).

I am getting error in console window since 6th Feb, 2018 as under:
"mixpanel-2-latest.min.js:9 Mixpanel error: "mixpanel" object not initialized. Ensure you are using the latest version of the Mixpanel JS Library along with the snippet we provide."

Could you please fix this issue as soon as possible?
Thanks.

**Comment by Esteban-Rocha** [comment]
Hi @shafqatali please read:
#101 #104 and #103
