### ISSUE TITLE
request: multiple measurements at the same time

### ISSUE THREAD

**Issue by aleksclark** [wrakky/page-ruler#47]
I'd like to be able to have multiple rulers/guides at the same time. Perhaps the easiest way would be to simply create more instances of the tool (at some level, chrome probably wouldn't let you _actually_ instantiate the extension twice). Picking colors for the guides/measurement bar would obviously be necessary...

**Comment by nickleus** [comment]
"Grid Ruler" does this, but it would b cool if PR implemented it bc atow GR seems quite buggy n lacks features that PR has. also, GR can measure at any angle in any direction, something i don't c PR offering, but which i would like :)

**Comment by matthewspeakman-wf** [comment]
+1
