### ISSUE TITLE
Ability to lock ruler

### ISSUE THREAD

**Issue by omarwebuycars** [wrakky/page-ruler#52]
I can't find a way to lock the Ruler. I love this plugin, but once my area is set and I want to be able to click around and zoom in and out I can't find a way to keep my grid lines in place. I looked through the documentation (at least what I could find) and didn't find an option. This would be awesome to be able to do. If it is already there and i'm being retarded, I apologize in advance. 

Thanks! You guys rock! Great plugin!

**Comment by AndrewBogdanovTSS** [comment]
Adding to that I would like to have pointer-events set to "none" when ruler is locked. That way it will be possible to select elements under a ruler with a tool from dev tools.

**Comment by AndrewBogdanovTSS** [comment]
Why was this request silently closed? Was anything done in order to fulfill it?
