### ISSUE TITLE
Suggestion: a possibility to change the cross color

### ISSUE THREAD

**Issue by sherstyuk** [wrakky/page-ruler#56]
Hi there
Is it possible to add a possibility to change the cross color? It's very very uncomfortable to measure things on black page elements like here http://awesomescreenshot.com/0c34jhy157.
Thanks in advance.

**Comment by wrakky** [comment]
Thanks for the feedback! An updated marker icon which makes it easier to see on dark backgrounds will be available in the next release shortly.

**Comment by abnmt** [comment]
Thank you! I'm also really looking forward to this update.
