### ISSUE TITLE
Please help - phantom lines won't go away

### ISSUE THREAD

**Issue by kpharr** [wrakky/page-ruler#64]
Hello,

I installed your app back in December, and then uninstalled it after I realized that the dotted ruler lines were appearing on my computer sporadically when I wasn't trying to measure anything. Now, every couple of hours or so, I see these dotted lines again, even though I no longer have the ruler installed. The only way to make them go away is to restart my computer. Can you please help? :(

**Comment by wrakky** [comment]
Hey sorry to hear about this :( I've got no idea why this would be happening and have never heard of it before. I can only guess about a possible solution. Do the lines always appear in the same place and with the same colour? 

I would suggest trying the following if you haven't already:
* See if the extension still exists in your chrome profile (http://stackoverflow.com/questions/14543896/where-does-chrome-store-extensions) maybe it was not uninstalled correctly. Look for the folder called jlpkojjdgbllmedoapgfodplfhcbnbpn and delete it.
* Install Page Ruler again and uninstall it again
* Create a new chrome profile and see if it still happens
* Uninstall chrome and reinstall it

I hope this helps and sorry for the problems :(
