### ISSUE TITLE
Not working for local pages

### ISSUE THREAD

**Issue by elstr** [wrakky/page-ruler#71]
This is a great tool but It doesn't work for local pages. :(

**Comment by wrakky** [comment]
You can enable this with the "Allow access to file URLs" option for the extension in the chrome://extensions/ page

**Comment by Dorrator** [comment]
It is worth adding a prompt. Something like that:
![image](https://user-images.githubusercontent.com/16753866/31477327-0cb026c0-af14-11e7-8f00-72b30428000d.png)
