### ISSUE TITLE
Permissions on local html files

### ISSUE THREAD

**Issue by dobrik** [wrakky/page-ruler#75]
Hello. Ruler don't work with local files. I got error
`extensions::lastError:131 Unchecked runtime.lastError while running tabs.executeScript: Cannot access contents of url "file:///D:/designs/chinar/room.html". Extension manifest must request permission to access this host.
    at browserAction (chrome-extension://jlpkojjdgbllmedoapgfodplfhcbnbpn/background.js:1:1658)`

**Comment by mtpetros** [comment]
Chrome does not allow extensions access to local pages by default. To allow the extension to access local files you must go the settings > extensions > under "Page Ruler" check "Allow access to file URLs."

**Comment by dobrik** [comment]
Thanks!

**Comment by rafaeldwan** [comment]
Putting these instructions in a readme or somewhere on the options page would be useful.

**Comment by kiditran** [comment]
Yeah, thank you so much. It's solved

![1](https://user-images.githubusercontent.com/24970265/30575297-04403b70-9d2a-11e7-9396-44816ee1a1eb.png)
