### ISSUE TITLE
Broken links on #install page for Invigilator app links

### ISSUE THREAD

**Issue by b2397** [wrakky/page-ruler#79]
![image](https://cloud.githubusercontent.com/assets/15827666/22085967/8b230d98-dda4-11e6-89d4-002e34d18798.png)

https://chrome.google.com/webstore/detail/invigilator/gmhgjkobbgamddnpceaieojogffcmckh?utm_source=page_ruler&utm_medium=update_page&utm_campaign=page_ruler

![image](https://cloud.githubusercontent.com/assets/15827666/22085997/a90e941c-dda4-11e6-890d-fca78fe79180.png)

**Comment by pointyointment** [comment]
Invigilator seems to be discontinued :(
