### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by TerranRich** [wrakky/page-ruler#99]
It would be great to have keyboard shortcuts. For example, just to toggle the ruler on/off it's a hassle to drag my mouse all the way to the top-right of the browser (I have a huge monitor and screen space, being a developer) and then back to the viewport so I can use the ruler tool. A keyboard shortcut to toggle it on/off would be great.

Can't think of any other shortcuts that could be added. This is the most important one, I think.

**Comment by wrakky** [comment]
This should already be a feature - see the "Keyboard Shortcuts" link at the bottom of the chrome://extensions/ page

**Comment by TerranRich** [comment]
I didn't even know this was a thing in Chrome. Sorry. Thank you for the gentle correction.
